#!/usr/bin/env python3
"""Writes the SEO artefacts into a directory holding a built frontend.

The head of `index.html` is rewritten in place and `robots.txt`, `sitemap.xml`
and `og-image.png` are written beside it, from the canonical domain passed on
the command line and the site owner read out of the production seed. When the
domain or the seed is missing, unreadable or still holds a template
placeholder, nothing is written and the run exits 0.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from og_image import render_card

INDEX_FILE = "index.html"
ROBOTS_FILE = "robots.txt"
SITEMAP_FILE = "sitemap.xml"
OG_IMAGE_FILE = "og-image.png"

#: Production seed, as the repository root holds it.
DEFAULT_SEED = Path("database/prod-initdb.d/500_prod_seed.sql")

#: Length at which the meta description is trimmed.
DESCRIPTION_LIMIT = 160

#: Contact types whose values are public profiles elsewhere.
PROFILE_CONTACTS = ("github", "linkedin", "website")

#: Crawlers named individually so each gets an explicit allow rule.
NAMED_CRAWLERS = ("Googlebot", "Bingbot", "GPTBot", "ClaudeBot", "PerplexityBot")

#: Comments wrapping the injected tags, which mark the block for replacement on a rerun.
BLOCK_OPEN = "<!-- Generated by tools/seo -->"
BLOCK_CLOSE = "<!-- End of tools/seo -->"

#: Values the templates ship, standing in for a deployment that has none of its own.
PLACEHOLDER_HOST = re.compile(r"(^|\.)(example\.(com|org|net)|yourdomain\.com)$", re.IGNORECASE)
PLACEHOLDER_EMAIL = re.compile(r"@example\.(com|org|net)$", re.IGNORECASE)
PLACEHOLDER_TEXT = ("your name", "your title")

GENERATED_BLOCK = re.compile(
    rf"[ \t]*{re.escape(BLOCK_OPEN)}.*?{re.escape(BLOCK_CLOSE)}\n?", re.DOTALL
)
TITLE_ELEMENT = re.compile(r"<title>.*?</title>", re.IGNORECASE | re.DOTALL)
HTML_LANG = re.compile(r"<html[^>]*\slang=[\"']([^\"']+)[\"']", re.IGNORECASE)
HEAD_CLOSE = re.compile(r"</head\s*>", re.IGNORECASE)

#: A MySQL string literal, in which a quote is doubled or backslash-escaped.
LITERAL = r"'(?:[^'\\]|''|\\.)*'"
#: One `( ... )` tuple of the VALUES list, and one value inside such a tuple.
VALUES_TUPLE = re.compile(rf"[\s,]*\(((?:[^()']|{LITERAL})*)\)")
VALUE = re.compile(rf"\s*{LITERAL}\s*|[^,]+")
ESCAPE = re.compile(r"''|\\(.)", re.DOTALL)
ESCAPED_CHARACTERS = {"0": "\0", "b": "\b", "n": "\n", "r": "\r", "t": "\t", "Z": "\x1a"}

Row = dict[str, str | None]
Log = Callable[[str], None]


def decode_value(token: str) -> str | None:
    """One value from a VALUES tuple, unquoted and unescaped, with NULL reading as None."""
    token = token.strip()
    if token.upper() == "NULL":
        return None
    if not token.startswith("'"):
        return token

    def unescape(match: re.Match[str]) -> str:
        escaped = match.group(1)
        return "'" if escaped is None else ESCAPED_CHARACTERS.get(escaped, escaped)

    return ESCAPE.sub(unescape, token[1:-1])


def read_rows(sql: str, table: str) -> list[Row]:
    """The rows of the first `INSERT INTO <table>` statement, keyed by column name."""
    header = re.search(rf"INSERT\s+INTO\s+`?{table}`?\s*\(([^)]*)\)\s*VALUES", sql, re.IGNORECASE)
    if header is None:
        return []

    columns = [column.strip().strip("`") for column in header.group(1).split(",")]
    rows: list[Row] = []
    index = header.end()

    while (row := VALUES_TUPLE.match(sql, index)) is not None:
        values = [decode_value(token) for token in VALUE.findall(row.group(1))]
        rows.append(dict(zip(columns, values)))
        index = row.end()

    return rows


def column(row: Row, name: str) -> str:
    """The trimmed value of a column, with a missing or NULL column reading as empty."""
    value = row.get(name)
    return value.strip() if isinstance(value, str) else ""


def summarise(bio: str, fallback: str) -> str:
    """The bio on one line, trimmed on a word boundary at the description limit."""
    body = " ".join(bio.split())
    if not body:
        return fallback
    if len(body) <= DESCRIPTION_LIMIT:
        return body

    clipped = body[: DESCRIPTION_LIMIT - 1]
    kept = clipped[: clipped.rfind(" ")] if " " in clipped else clipped
    return f"{kept.rstrip(',;:.')}…"


def read_host(site_url: str | None) -> str | None:
    """The bare hostname `site_url` names, or None when it names no deployed domain."""
    host = re.sub(r"^https?://", "", (site_url or "").strip().lower())
    host = re.sub(r"^www\.", "", host.split("/")[0].split(":")[0])

    if not host or "." not in host or re.search(r"[\s,]", host):
        return None

    return None if PLACEHOLDER_HOST.search(host) else host


@dataclass(frozen=True)
class Site:
    """The person and the domain every artefact is drawn from."""

    host: str
    name: str
    role: str
    description: str
    profile_image: str | None
    email: str | None
    same_as: tuple[str, ...]
    skills: tuple[str, ...]

    @property
    def origin(self) -> str:
        return f"https://{self.host}"

    @property
    def canonical(self) -> str:
        return f"{self.origin}/"

    @property
    def page_title(self) -> str:
        return f"{self.name} | {self.role}"


def read_site(seed_sql: str, host: str) -> Site | None:
    """The site owner the seed inserts, or None when it holds no usable person."""
    users = read_rows(seed_sql, "users")
    if not users:
        return None

    name = column(users[0], "name")
    role = column(users[0], "title")
    contacts = [
        (column(row, "type").lower(), column(row, "value"))
        for row in read_rows(seed_sql, "contact_info")
    ]
    email = next((value for kind, value in contacts if kind == "email"), None)

    if not name or not role or {name.lower(), role.lower()} & set(PLACEHOLDER_TEXT):
        return None
    if email and PLACEHOLDER_EMAIL.search(email):
        return None

    return Site(
        host=host,
        name=name,
        role=role,
        description=summarise(column(users[0], "bio"), f"{name} — {role}"),
        profile_image=column(users[0], "profileImage").lstrip("/") or None,
        email=email,
        # A profile on the site's own host is the canonical URL, not a profile elsewhere.
        same_as=tuple(
            value for kind, value in contacts if kind in PROFILE_CONTACTS and host not in value
        ),
        skills=tuple(
            skill for row in read_rows(seed_sql, "skills") if (skill := column(row, "skill"))
        ),
    )


def build_json_ld(site: Site, language: str) -> dict[str, object]:
    """The schema.org graph describing the person, the page and the site."""
    person: dict[str, object] = {
        "@type": "Person",
        "@id": f"{site.origin}/#person",
        "name": site.name,
        "url": site.canonical,
        "jobTitle": site.role,
        "description": site.description,
    }

    if site.profile_image:
        person["image"] = f"{site.origin}/{site.profile_image}"
    if site.email:
        person["email"] = f"mailto:{site.email}"
    if site.same_as:
        person["sameAs"] = list(site.same_as)

    page = {
        "@type": "ProfilePage",
        "@id": f"{site.origin}/#profilepage",
        "url": site.canonical,
        "name": site.page_title,
        "description": site.description,
        "inLanguage": language,
        "isPartOf": {"@id": f"{site.origin}/#website"},
        "mainEntity": {"@id": f"{site.origin}/#person"},
    }
    website = {
        "@type": "WebSite",
        "@id": f"{site.origin}/#website",
        "url": site.canonical,
        "name": site.name,
        "inLanguage": language,
    }

    return {"@context": "https://schema.org", "@graph": [person, page, website]}


def build_head_tags(site: Site, language: str) -> list[str]:
    """The head elements for the document.

    Twitter reads the Open Graph tags, so only the card type is declared for it.
    The JSON-LD body is inserted with `<` written as an escape, so the payload
    cannot close the script element early.
    """
    meta = {
        "description": site.description,
        "og:type": "profile",
        "og:title": site.page_title,
        "og:description": site.description,
        "og:url": site.canonical,
        "og:image": f"{site.origin}/{OG_IMAGE_FILE}",
        "og:image:width": "1200",
        "og:image:height": "630",
        "og:image:alt": f"{site.name}, {site.role}",
        "twitter:card": "summary_large_image",
    }
    json_ld = json.dumps(build_json_ld(site, language), indent=2, ensure_ascii=False)
    payload = json_ld.replace("<", "\\u003c")

    return [
        f'<link rel="canonical" href="{html.escape(site.canonical, quote=True)}" />',
        *(
            f'<meta {"property" if key.startswith("og:") else "name"}="{key}" '
            f'content="{html.escape(value, quote=True)}" />'
            for key, value in meta.items()
        ),
        f'<script type="application/ld+json">{payload}</script>',
    ]


def inject_head(document: str, site: Site) -> str:
    """The document with its title rewritten and the generated block in its head.

    A block left by an earlier run is replaced, so the result is the same
    however many times the generator runs over the same file.
    """
    language = HTML_LANG.search(document)
    title = html.escape(site.page_title, quote=False)
    updated = TITLE_ELEMENT.sub(
        lambda _match: f"<title>{title}</title>", GENERATED_BLOCK.sub("", document), count=1
    )

    tags = build_head_tags(site, language.group(1) if language else "en")
    block = "".join(f"    {line}\n" for line in (BLOCK_OPEN, *tags, BLOCK_CLOSE))

    head_close = HEAD_CLOSE.search(updated)
    if head_close is None:
        return updated + block

    return updated[: head_close.start()] + block + "  " + updated[head_close.start() :]


def render_robots(site: Site) -> str:
    """robots.txt, allowing every named crawler and pointing at the sitemap."""
    groups = "\n".join(f"User-agent: {agent}\nAllow: /\n" for agent in ("*", *NAMED_CRAWLERS))
    return f"{groups}\nSitemap: {site.origin}/{SITEMAP_FILE}\n"


def render_sitemap(site: Site) -> str:
    """sitemap.xml, which lists the single page the site serves."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{site.canonical}</loc>
    <lastmod>{date.today().isoformat()}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
"""


def generate(build_dir: Path, site_url: str | None, seed: Path, log: Log = print) -> bool:
    """Writes the artefacts into `build_dir`, or logs why it wrote none."""

    def omit(reason: str) -> bool:
        log(f"seo: omitting the SEO artefacts — {reason}")
        return False

    index = build_dir / INDEX_FILE
    if not index.is_file():
        return omit(f"{index} does not exist")

    host = read_host(site_url)
    if host is None:
        return omit("SITE_URL names no deployed domain")

    try:
        seed_sql = seed.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return omit(f"{seed} is not readable")

    site = read_site(seed_sql, host)
    if site is None:
        return omit(f"{seed} holds no usable person")

    log(f"seo: generating the SEO artefacts for {site.host}")
    photo = build_dir / (site.profile_image or "")
    card = render_card(
        site.name,
        site.role,
        site.skills,
        site.host,
        photo.read_bytes() if site.profile_image and photo.is_file() else None,
        build_dir,
    )

    index.write_text(inject_head(index.read_text(encoding="utf-8"), site), encoding="utf-8")
    (build_dir / ROBOTS_FILE).write_text(render_robots(site), encoding="utf-8")
    (build_dir / SITEMAP_FILE).write_text(render_sitemap(site), encoding="utf-8")
    (build_dir / OG_IMAGE_FILE).write_bytes(card)

    log(f"seo: wrote {INDEX_FILE}, {ROBOTS_FILE}, {SITEMAP_FILE}, {OG_IMAGE_FILE}")
    return True


def main(argv: list[str] | None = None) -> int:
    """Runs the generator and returns the process exit status."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, required=True, help="the built frontend")
    parser.add_argument("--site-url", default="", help="canonical domain of the deployment")
    parser.add_argument(
        "--seed", type=Path, default=DEFAULT_SEED, help="production seed (default: %(default)s)"
    )
    options = parser.parse_args(argv)

    generate(options.build_dir, options.site_url, options.seed)
    return 0


if __name__ == "__main__":
    sys.exit(main())
