"""Turns a site host and a site owner into the document head, the crawler files
and the values the social card is drawn from.
"""

from __future__ import annotations

import html
import json
import re
from dataclasses import dataclass
from urllib.parse import urlparse

from .seed import SiteOwner

OG_IMAGE_FILE = "og-image.png"
ROBOTS_FILE = "robots.txt"
SITEMAP_FILE = "sitemap.xml"
INDEX_FILE = "index.html"

#: Length at which the meta description is trimmed.
DESCRIPTION_LIMIT = 160

#: Contact types whose values are public profiles elsewhere.
PROFILE_CONTACT_TYPES = ("github", "linkedin", "website")

#: Crawlers named individually so each gets an explicit allow rule.
NAMED_CRAWLERS = ("Googlebot", "Bingbot", "GPTBot", "ClaudeBot", "PerplexityBot")

#: Comments wrapping the injected tags, which mark the block for replacement on a rerun.
BLOCK_OPEN = "<!-- Generated by tools/seo -->"
BLOCK_CLOSE = "<!-- End of tools/seo -->"

SENTENCE_BREAK = re.compile(r"(?<=[.!?])\s+")
GENERATED_BLOCK = re.compile(
    rf"[ \t]*{re.escape(BLOCK_OPEN)}.*?{re.escape(BLOCK_CLOSE)}\n?",
    re.DOTALL,
)
TITLE_ELEMENT = re.compile(r"<title>.*?</title>", re.IGNORECASE | re.DOTALL)
HTML_LANG = re.compile(r"<html[^>]*\slang=[\"']([^\"']+)[\"']", re.IGNORECASE)
HEAD_CLOSE = re.compile(r"</head\s*>", re.IGNORECASE)
LEADING_SLASHES = re.compile(r"^/+")


@dataclass(frozen=True)
class SiteMetadata:
    """Everything the head tags, the crawler files and the social card are drawn from."""

    host: str
    origin: str
    canonical: str
    page_title: str
    description: str
    name: str
    job_title: str
    og_image_url: str
    og_image_alt: str
    #: Profile photo as the built frontend serves it, relative to the build directory.
    profile_image_path: str | None
    profile_image_url: str | None
    email: str | None
    same_as: tuple[str, ...] = ()
    employer: str | None = None
    institution: str | None = None
    skills: tuple[str, ...] = ()


def collapse(value: str) -> str:
    """The value with every run of whitespace reduced to a single space."""
    return " ".join(value.split())


def summarise(bio: str, fallback: str) -> str:
    """Keeps whole sentences up to the description limit, trimming on a word boundary otherwise."""
    body = collapse(bio)
    if not body:
        return fallback
    if len(body) <= DESCRIPTION_LIMIT:
        return body

    summary = ""
    for sentence in SENTENCE_BREAK.split(body):
        candidate = f"{summary} {sentence}" if summary else sentence
        if len(candidate) > DESCRIPTION_LIMIT:
            break
        summary = candidate
    if summary:
        return summary

    clipped = body[: DESCRIPTION_LIMIT - 1]
    last_space = clipped.rfind(" ")
    kept = clipped[:last_space] if last_space > 0 else clipped
    return f"{kept.rstrip(',;:.')}…"


def hostname_of(value: str) -> str | None:
    """The hostname of an absolute http(s) URL, without any `www.` prefix."""
    if not re.match(r"^https?://", value, re.IGNORECASE):
        return None

    hostname = urlparse(value).hostname
    if not hostname:
        return None

    return re.sub(r"^www\.", "", hostname.lower())


def build_metadata(owner: SiteOwner, host: str) -> SiteMetadata:
    """Combines the site owner and the canonical host into the values every artefact uses."""
    origin = f"https://{host}"
    email = next((contact.value for contact in owner.contacts if contact.type == "email"), None)
    apex = re.sub(r"^www\.", "", host)

    # A profile on the site's own host is the canonical URL, not a profile elsewhere.
    same_as = tuple(
        contact.value
        for contact in owner.contacts
        if contact.type in PROFILE_CONTACT_TYPES
        and (hostname := hostname_of(contact.value)) is not None
        and hostname != apex
    )

    profile_image = LEADING_SLASHES.sub("", owner.profile_image) if owner.profile_image else None

    return SiteMetadata(
        host=host,
        origin=origin,
        canonical=f"{origin}/",
        page_title=f"{owner.name} | {owner.title}",
        description=summarise(owner.bio, f"{owner.name} — {owner.title}"),
        name=owner.name,
        job_title=owner.title,
        og_image_url=f"{origin}/{OG_IMAGE_FILE}",
        og_image_alt=f"{owner.name}, {owner.title}",
        profile_image_path=profile_image,
        profile_image_url=f"{origin}/{profile_image}" if profile_image else None,
        email=email,
        same_as=same_as,
        employer=owner.employer,
        institution=owner.institution,
        skills=owner.skills,
    )


def build_json_ld(metadata: SiteMetadata, language: str) -> dict[str, object]:
    """Builds the schema.org graph describing the person, the page and the site."""
    person: dict[str, object] = {
        "@type": "Person",
        "@id": f"{metadata.origin}/#person",
        "name": metadata.name,
        "url": metadata.canonical,
        "jobTitle": metadata.job_title,
        "description": metadata.description,
    }

    if metadata.profile_image_url:
        person["image"] = metadata.profile_image_url
    if metadata.email:
        person["email"] = f"mailto:{metadata.email}"
    if metadata.employer:
        person["worksFor"] = {"@type": "Organization", "name": metadata.employer}
    if metadata.institution:
        person["alumniOf"] = {"@type": "CollegeOrUniversity", "name": metadata.institution}
    if metadata.same_as:
        person["sameAs"] = list(metadata.same_as)

    return {
        "@context": "https://schema.org",
        "@graph": [
            person,
            {
                "@type": "ProfilePage",
                "@id": f"{metadata.origin}/#profilepage",
                "url": metadata.canonical,
                "name": metadata.page_title,
                "description": metadata.description,
                "inLanguage": language,
                "isPartOf": {"@id": f"{metadata.origin}/#website"},
                "mainEntity": {"@id": f"{metadata.origin}/#person"},
            },
            {
                "@type": "WebSite",
                "@id": f"{metadata.origin}/#website",
                "url": metadata.canonical,
                "name": metadata.name,
                "inLanguage": language,
            },
        ],
    }


def _tag(name: str, attributes: dict[str, str]) -> str:
    rendered = " ".join(
        f'{key}="{html.escape(value, quote=True)}"' for key, value in attributes.items()
    )
    return f"<{name} {rendered} />"


def build_head_tags(metadata: SiteMetadata, language: str) -> list[str]:
    """Builds the head elements for the document.

    The JSON-LD body is inserted verbatim, with `<` written as an escape so the
    payload cannot close the script element early.
    """
    json_ld = json.dumps(build_json_ld(metadata, language), indent=2, ensure_ascii=False)

    return [
        _tag("link", {"rel": "canonical", "href": metadata.canonical}),
        _tag("meta", {"name": "description", "content": metadata.description}),
        _tag("meta", {"property": "og:type", "content": "profile"}),
        _tag("meta", {"property": "og:title", "content": metadata.page_title}),
        _tag("meta", {"property": "og:description", "content": metadata.description}),
        _tag("meta", {"property": "og:url", "content": metadata.canonical}),
        _tag("meta", {"property": "og:image", "content": metadata.og_image_url}),
        _tag("meta", {"property": "og:image:width", "content": "1200"}),
        _tag("meta", {"property": "og:image:height", "content": "630"}),
        _tag("meta", {"property": "og:image:alt", "content": metadata.og_image_alt}),
        _tag("meta", {"name": "twitter:card", "content": "summary_large_image"}),
        _tag("meta", {"name": "twitter:title", "content": metadata.page_title}),
        _tag("meta", {"name": "twitter:description", "content": metadata.description}),
        _tag("meta", {"name": "twitter:image", "content": metadata.og_image_url}),
        _tag("meta", {"name": "twitter:image:alt", "content": metadata.og_image_alt}),
        '<script type="application/ld+json">' + json_ld.replace("<", "\\u003c") + "</script>",
    ]


def read_html_lang(document: str) -> str:
    """The `lang` attribute of the document, which the metadata declares as the page language."""
    match = HTML_LANG.search(document)
    return match.group(1) if match else "en"


def replace_title(document: str, title: str) -> str:
    """Rewrites the document's `<title>` element."""
    escaped = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return TITLE_ELEMENT.sub(f"<title>{escaped}</title>", document, count=1)


def inject_head(document: str, metadata: SiteMetadata) -> str:
    """Returns the document with the title rewritten and the generated block in its head.

    A block left by an earlier run is replaced, so the result is the same however
    many times the generator runs over the same file.
    """
    language = read_html_lang(document)
    stripped = GENERATED_BLOCK.sub("", document)
    updated = replace_title(stripped, metadata.page_title)

    lines = [BLOCK_OPEN, *build_head_tags(metadata, language), BLOCK_CLOSE]
    block = "".join(f"    {line}\n" for line in lines)

    match = HEAD_CLOSE.search(updated)
    if match is None:
        return updated + block

    return updated[: match.start()] + block + "  " + updated[match.start() :]


def render_robots_txt(metadata: SiteMetadata) -> str:
    """Renders robots.txt, allowing every named crawler and pointing at the sitemap."""
    groups = "\n".join(f"User-agent: {agent}\nAllow: /\n" for agent in ("*", *NAMED_CRAWLERS))
    return f"{groups}\nSitemap: {metadata.origin}/{SITEMAP_FILE}\n"


def render_sitemap_xml(metadata: SiteMetadata, last_modified: str) -> str:
    """Renders sitemap.xml, which lists the single page the site serves."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{metadata.canonical}</loc>
    <lastmod>{last_modified}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
"""
